{"name": "test_003", "status": "failed", "statusDetails": {"message": "Failed: Test failed due to exception: Message: stale element reference: stale element not found\n  (Session info: chrome=134.0.6998.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF663E3FE45+26629]\n\t(No symbol) [0x00007FF663DA6010]\n\t(No symbol) [0x00007FF663C3931A]\n\t(No symbol) [0x00007FF663C4F424]\n\t(No symbol) [0x00007FF663C4DEF3]\n\t(No symbol) [0x00007FF663C419A9]\n\t(No symbol) [0x00007FF663C3F782]\n\t(No symbol) [0x00007FF663C43A3C]\n\t(No symbol) [0x00007FF663C43B0F]\n\t(No symbol) [0x00007FF663C9074A]\n\t(No symbol) [0x00007FF663C90817]\n\t(No symbol) [0x00007FF663C860FA]\n\t(No symbol) [0x00007FF663CB7AAA]\n\t(No symbol) [0x00007FF663C82156]\n\t(No symbol) [0x00007FF663CB7CC0]\n\t(No symbol) [0x00007FF663CE0169]\n\t(No symbol) [0x00007FF663CB7883]\n\t(No symbol) [0x00007FF663C80550]\n\t(No symbol) [0x00007FF663C81803]\n\tGetHandleVerifier [0x00007FF6641972BD+3529853]\n\tGetHandleVerifier [0x00007FF6641ADA22+3621858]\n\tGetHandleVerifier [0x00007FF6641A24D3+3575443]\n\tGetHandleVerifier [0x00007FF663F0B77A+860474]\n\t(No symbol) [0x00007FF663DB088F]\n\t(No symbol) [0x00007FF663DACBC4]\n\t(No symbol) [0x00007FF663DACD66]\n\t(No symbol) [0x00007FF663D9C2C9]\n\tBaseThreadInitThunk [0x00007FFB21397374+20]\n\tRtlUserThreadStart [0x00007FFB2321CC91+33]", "trace": "self = <tests.test_001.Test_001 object at 0x0000020FB4CD7910>, setUp = None\n\n    @pytest.mark.e2e\n    def test_003(self, setUp):\n        ''' this test case will book a suite and make a pre order'''\n        try:\n            # cancel all available new orders\n            cancelOrder = CancelOrders()\n            cancelOrder.cancel_new_orders()\n    \n            home_page = HomePage(driver=self.driver)\n            home_page.open('')\n            # read data from excel\n            credentials = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Login credentials\")\n            event_details = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Event details\")\n            card_details = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Card details\")\n    \n>           home_page.login(credentials['Email'][0],credentials['Password'][0])\n\ntests\\test_001.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPages\\home_page.py:21: in login\n    self.driver.find_element(*self.locator.EMAIL).send_keys(email)\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:231: in send_keys\n    self._execute(\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:395: in _execute\n    return self._parent.execute(command, params)\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:348: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000020FB4D05610>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...07FF663D9C2C9]\\\\n\\\\tBaseThreadInitThunk [0x00007FFB21397374+20]\\\\n\\\\tRtlUserThreadStart [0x00007FFB2321CC91+33]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\nE         (Session info: chrome=134.0.6998.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF663E3FE45+26629]\nE       \t(No symbol) [0x00007FF663DA6010]\nE       \t(No symbol) [0x00007FF663C3931A]\nE       \t(No symbol) [0x00007FF663C4F424]\nE       \t(No symbol) [0x00007FF663C4DEF3]\nE       \t(No symbol) [0x00007FF663C419A9]\nE       \t(No symbol) [0x00007FF663C3F782]\nE       \t(No symbol) [0x00007FF663C43A3C]\nE       \t(No symbol) [0x00007FF663C43B0F]\nE       \t(No symbol) [0x00007FF663C9074A]\nE       \t(No symbol) [0x00007FF663C90817]\nE       \t(No symbol) [0x00007FF663C860FA]\nE       \t(No symbol) [0x00007FF663CB7AAA]\nE       \t(No symbol) [0x00007FF663C82156]\nE       \t(No symbol) [0x00007FF663CB7CC0]\nE       \t(No symbol) [0x00007FF663CE0169]\nE       \t(No symbol) [0x00007FF663CB7883]\nE       \t(No symbol) [0x00007FF663C80550]\nE       \t(No symbol) [0x00007FF663C81803]\nE       \tGetHandleVerifier [0x00007FF6641972BD+3529853]\nE       \tGetHandleVerifier [0x00007FF6641ADA22+3621858]\nE       \tGetHandleVerifier [0x00007FF6641A24D3+3575443]\nE       \tGetHandleVerifier [0x00007FF663F0B77A+860474]\nE       \t(No symbol) [0x00007FF663DB088F]\nE       \t(No symbol) [0x00007FF663DACBC4]\nE       \t(No symbol) [0x00007FF663DACD66]\nE       \t(No symbol) [0x00007FF663D9C2C9]\nE       \tBaseThreadInitThunk [0x00007FFB21397374+20]\nE       \tRtlUserThreadStart [0x00007FFB2321CC91+33]\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: StaleElementReferenceException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_001.Test_001 object at 0x0000020FB4CD7910>, setUp = None\n\n    @pytest.mark.e2e\n    def test_003(self, setUp):\n        ''' this test case will book a suite and make a pre order'''\n        try:\n            # cancel all available new orders\n            cancelOrder = CancelOrders()\n            cancelOrder.cancel_new_orders()\n    \n            home_page = HomePage(driver=self.driver)\n            home_page.open('')\n            # read data from excel\n            credentials = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Login credentials\")\n            event_details = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Event details\")\n            card_details = home_page.read_excel(\"C:/Users/Foysal/Desktop/cheq_task/utils/info.xlsx\",\"Card details\")\n    \n            home_page.login(credentials['Email'][0],credentials['Password'][0])\n            home_page.select_Date_Event(event_details['Date'][0],event_details['Event name'][0])\n            home_page.select_suite(event_details['Suite name'][0])\n            home_page.select_suite_preference()\n            home_page.add_item()\n            total_before_preorder = home_page.submit_preorder()\n            home_page.select_credit_card()\n            total_after_preorder = home_page.enter_credit_card_details(card_details['Card no'][0],str(card_details['Exp_Date'][0]),card_details['CVC/CVV'][0],card_details['Name On Card'][0])\n    \n            assert str(total_before_preorder) == str(total_after_preorder)\n    \n        except Exception as e:\n            home_page.take_screenshot()\n>           home_page.log_info(e)\n\ntests\\test_001.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.home_page.HomePage object at 0x0000020FB4780750>, logs = StaleElementReferenceException()\n\n    @allure.step(\"Adding custom logs\")\n    def log_info(self,logs):\n        allure.attach(traceback.format_exc(), name=\"Selenium Error Traceback\", attachment_type=allure.attachment_type.TEXT)\n>       pytest.fail(f\"Test failed due to exception: {logs}\")\nE       Failed: Test failed due to exception: Message: stale element reference: stale element not found\nE         (Session info: chrome=134.0.6998.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF663E3FE45+26629]\nE       \t(No symbol) [0x00007FF663DA6010]\nE       \t(No symbol) [0x00007FF663C3931A]\nE       \t(No symbol) [0x00007FF663C4F424]\nE       \t(No symbol) [0x00007FF663C4DEF3]\nE       \t(No symbol) [0x00007FF663C419A9]\nE       \t(No symbol) [0x00007FF663C3F782]\nE       \t(No symbol) [0x00007FF663C43A3C]\nE       \t(No symbol) [0x00007FF663C43B0F]\nE       \t(No symbol) [0x00007FF663C9074A]\nE       \t(No symbol) [0x00007FF663C90817]\nE       \t(No symbol) [0x00007FF663C860FA]\nE       \t(No symbol) [0x00007FF663CB7AAA]\nE       \t(No symbol) [0x00007FF663C82156]\nE       \t(No symbol) [0x00007FF663CB7CC0]\nE       \t(No symbol) [0x00007FF663CE0169]\nE       \t(No symbol) [0x00007FF663CB7883]\nE       \t(No symbol) [0x00007FF663C80550]\nE       \t(No symbol) [0x00007FF663C81803]\nE       \tGetHandleVerifier [0x00007FF6641972BD+3529853]\nE       \tGetHandleVerifier [0x00007FF6641ADA22+3621858]\nE       \tGetHandleVerifier [0x00007FF6641A24D3+3575443]\nE       \tGetHandleVerifier [0x00007FF663F0B77A+860474]\nE       \t(No symbol) [0x00007FF663DB088F]\nE       \t(No symbol) [0x00007FF663DACBC4]\nE       \t(No symbol) [0x00007FF663DACD66]\nE       \t(No symbol) [0x00007FF663D9C2C9]\nE       \tBaseThreadInitThunk [0x00007FFB21397374+20]\nE       \tRtlUserThreadStart [0x00007FFB2321CC91+33]\n\nPages\\home_page.py:115: Failed"}, "description": " this test case will book a suite and make a pre order", "steps": [{"name": "Capturing screenshot", "status": "passed", "attachments": [{"name": "screenshot", "source": "128b2469-bda2-4ce0-83cc-7af43bb231c9-attachment.png", "type": "image/png"}], "parameters": [{"name": "name", "value": "'screenshot'"}], "start": 1742143291856, "stop": 1742143292078}, {"name": "Adding custom logs", "status": "failed", "statusDetails": {"message": "Failed: Test failed due to exception: Message: stale element reference: stale element not found\n  (Session info: chrome=134.0.6998.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF663E3FE45+26629]\n\t(No symbol) [0x00007FF663DA6010]\n\t(No symbol) [0x00007FF663C3931A]\n\t(No symbol) [0x00007FF663C4F424]\n\t(No symbol) [0x00007FF663C4DEF3]\n\t(No symbol) [0x00007FF663C419A9]\n\t(No symbol) [0x00007FF663C3F782]\n\t(No symbol) [0x00007FF663C43A3C]\n\t(No symbol) [0x00007FF663C43B0F]\n\t(No symbol) [0x00007FF663C9074A]\n\t(No symbol) [0x00007FF663C90817]\n\t(No symbol) [0x00007FF663C860FA]\n\t(No symbol) [0x00007FF663CB7AAA]\n\t(No symbol) [0x00007FF663C82156]\n\t(No symbol) [0x00007FF663CB7CC0]\n\t(No symbol) [0x00007FF663CE0169]\n\t(No symbol) [0x00007FF663CB7883]\n\t(No symbol) [0x00007FF663C80550]\n\t(No symbol) [0x00007FF663C81803]\n\tGetHandleVerifier [0x00007FF6641972BD+3529853]\n\tGetHandleVerifier [0x00007FF6641ADA22+3621858]\n\tGetHandleVerifier [0x00007FF6641A24D3+3575443]\n\tGetHandleVerifier [0x00007FF663F0B77A+860474]\n\t(No symbol) [0x00007FF663DB088F]\n\t(No symbol) [0x00007FF663DACBC4]\n\t(No symbol) [0x00007FF663DACD66]\n\t(No symbol) [0x00007FF663D9C2C9]\n\tBaseThreadInitThunk [0x00007FFB21397374+20]\n\tRtlUserThreadStart [0x00007FFB2321CC91+33]\n\n", "trace": "  File \"C:\\Users\\Foysal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Foysal\\Desktop\\cheq_task\\Pages\\home_page.py\", line 115, in log_info\n    pytest.fail(f\"Test failed due to exception: {logs}\")\n  File \"C:\\Users\\Foysal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "Selenium Error Traceback", "source": "476103ed-f51f-4c3e-8bad-d1be1473d564-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "logs", "value": "StaleElementReferenceException()"}], "start": 1742143292079, "stop": 1742143292385}], "attachments": [{"name": "stdout", "source": "daed2c71-0b8c-49be-83d6-deb9486267d0-attachment.txt", "type": "text/plain"}], "start": 1742143276502, "stop": 1742143292390, "uuid": "755e6f24-770b-4863-b8f6-915a7ee66652", "historyId": "8b247e80c44ccb5e7e9736305990cfa6", "testCaseId": "8b247e80c44ccb5e7e9736305990cfa6", "fullName": "tests.test_001.Test_001#test_003", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "e2e"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "DESKTOP-9TQTAC5"}, {"name": "thread", "value": "9292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_001"}]}